services:
  valkey:
    profiles: ["valkey", "all"]
    image: valkey/valkey:latest
    ports:
      - 6379:6379
    restart: always

  redis:
    profiles: ["redis", "all"]
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  keydb:
    profiles: ["keydb", "all"]
    image: eqalpha/keydb:latest
    ports:
      - 6379:6379
    restart: always

  dragonfly:
    profiles: ["dragonfly", "all"]
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - 6379:6379
    restart: always
