name = "valkyrie"
version = "1.0.1"

description = "A Gleam client for Valkey, KeyDB, Redis, Dragonfly and other Redis-compatible databases."
gleam = ">= 1.11.0"
licences = ["MIT"]
links = [
    { title = "Valkey", href = "https://valkey.io" },
    { title = "KeyDB", href = "https://keydb.dev" },
    { title = "Redis", href = "https://redis.io" },
    { title = "Dragonfly", href = "https://dragonflydb.io/" },
]
repository = { type = "github", user = "Pevensie", repo = "valkyrie" }

[dependencies]
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
mug = ">= 2.0.0 and < 3.0.0"
bath = ">= 4.1.0 and < 5.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.5.1 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
