name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          [
            valkey/valkey:7,
            valkey/valkey:8,
            redis:7,
            redis:8,
            eqalpha/keydb:latest,
            docker.dragonflydb.io/dragonflydb/dragonfly,
          ]
        version: [7, 8]
    services:
      valkey:
        image: ${{ matrix.image }}:${{ matrix.version }}
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.11"
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
